"""add table employees

Revision ID: 5afd515bf452
Revises: 0a36ea1ca01e
Create Date: 2025-11-14 12:34:56.931361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afd515bf452'
down_revision: Union[str, Sequence[str], None] = '0a36ea1ca01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contacts', sa.Column('responsible_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'employees', ['responsible_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('deals', sa.Column('responsible_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'deals', 'employees', ['responsible_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'responsible_user_id')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'responsible_user_id')
    op.drop_table('employees')
    # ### end Alembic commands ###
