"""add closed_at in Deal table

Revision ID: 698f458677a7
Revises: 23723542d4aa
Create Date: 2025-12-08 22:20:05.180870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698f458677a7'
down_revision: Union[str, Sequence[str], None] = '23723542d4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'closed_at')
    # ### end Alembic commands ###
