"""add column hashed_password in Employee table

Revision ID: a1f3f64b51da
Revises: 5afd515bf452
Create Date: 2025-11-14 16:14:46.820920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f3f64b51da'
down_revision: Union[str, Sequence[str], None] = '5afd515bf452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'hashed_password')
    # ### end Alembic commands ###
