"""update model Employee and Contact

Revision ID: daa1ada3cbe9
Revises: a1f3f64b51da
Create Date: 2025-11-22 18:24:15.906602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa1ada3cbe9'
down_revision: Union[str, Sequence[str], None] = 'a1f3f64b51da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('telegram_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'contacts', ['telegram_id'])
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint(None, 'employees', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'is_active')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'telegram_id')
    # ### end Alembic commands ###
